<?php

define('TENANT_ACTIVE', 1);

return [
    'is_delivery_online' => true,
    'ghn' => 'ghn',
    'ghtk' => 'ghtk',
    'viettelpost' => 'viettelpost',
    'bestexpress' => 'bestexpress',
    'dhl' => 'dhl',
    'api_provinces_full' => 'https://provinces.open-api.vn/api/?depth=3',
    'api_provinces' => 'https://provinces.open-api.vn/api/',
    'pick_shift_ghtk' => [
        '2' => 'Lấy trước 8h30 & Giao trước 10h30',
        '5' => 'Lấy trước 10h30 & Giao trước 12h30',
        '8' => 'Lấy trước 13h30 & Giao trước 15h30',
        '11' => 'Lấy trước 15h30 & Giao trước 17h30',
        '2_mai' => 'Lấy trước 8h30 & Giao trước 10h30 ngày mai',
        '5_mai' => 'Lấy trước 10h30 & Giao trước 12h30 ngày mai',
        '8_mai' => 'Lấy trước 13h30 & Giao trước 15h30 ngày mai',
        '11_mai' => 'Lấy trước 15h30 & Giao trước 17h30 ngày mai',
    ],
    'is_breakable' => 1,
    'is_food' => 7,
    'kg_to_gram' => 1000,
    'is_freeship' => 1,
    'max_insurance_ghtk' => 250000,
    'insurance_ghtk' => 1000000,
    'ghtk_status_order' => [
        '-1' => 'Hủy đơn hàng',
        '1' => 'Chưa tiếp nhận',
        '2' => 'Đã tiếp nhận',
        '3' => 'Đã lấy hàng/Đã nhập kho',
        '4' => 'Đã điều phối giao hàng/Đang giao hàng',
        '5' => 'Đã giao hàng/Chưa đối soát',
        '6' => 'Đã đối soát',
        '7' => 'Không lấy được hàng',
        '8' => 'Hoãn lấy hàng',
        '9' => 'Không giao được hàng',
        '10' => 'Delay giao hàng',
        '11' => 'Đã đối soát công nợ trả hàng',
        '12' => 'Đã điều phối lấy hàng/Đang lấy hàng',
        '13' => 'Đơn hàng bồi hoàn',
        '20' => 'Đang trả hàng (COD cầm hàng đi trả)',
        '21' => 'Đã trả hàng (COD đã trả xong hàng)',
        '123' => 'Shipper báo đã lấy hàng',
        '127' => 'Shipper (nhân viên lấy/giao hàng) báo không lấy được hàng',
        '128' => 'Shipper báo delay lấy hàng',
        '45' => 'Shipper báo đã giao hàng',
        '49' => 'Shipper báo không giao được giao hàng',
        '410' => 'Shipper báo delay giao hàng',
    ],
    'ghn_status_order' => [
        'ready_to_pick' => "Chờ bàn giao",
        'picking' => "Nhân viên đang lấy hàng",
        'cancel' => "Hủy đơn hàng",
        'picked' => "Nhân viên đã lấy hàng",
        'storing' => "Hàng đang nằm ở kho",
        'transporting' => "Đang luân chuyển hàng",
        'delivering' => "Nhân viên đang giao cho người nhận",
        'money_collect_delivering' => "Nhân viên đang thu tiền người nhận",
        'delivered' => "Nhân viên đã giao hàng thành công",
        'delivery_fail' => "Nhân viên giao hàng thất bại",
        'waiting_to_return' => "Đang đợi trả hàng về cho người gửi",
        'return' => "Trả hàng",
        'return_transporting' => "Đang luân chuyển hàng trả",
        'return_sorting' => "Đang phân loại hàng trả",
        'returning' => "Nhân viên đang đi trả hàng",
        'return_fail' => "Nhân viên trả hàng thất bại",
        'returned' => "Nhân viên trả hàng thành công",
        'exception' => "Đơn hàng ngoại lệ không nằm trong quy trình",
        'damage' => "Hàng bị hư hỏng",
        'lost' => "Hàng bị mất",
    ],
];
